# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ore/base.proto\x12\x04jagw\"G\n\x17MultiTopologyIdentifier\x12\x0e\n\x06o_flag\x18\x01 \x02(\x08\x12\x0e\n\x06\x61_flag\x18\x02 \x02(\x08\x12\x0c\n\x04mtid\x18\x03 \x02(\rB.Z,github.com/jalapeno-api-gateway/jagw-go;jagw')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.base_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/jalapeno-api-gateway/jagw-go;jagw'
  _MULTITOPOLOGYIDENTIFIER._serialized_start=25
  _MULTITOPOLOGYIDENTIFIER._serialized_end=96
# @@protoc_insertion_point(module_scope)
